name: localmeapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.9
  firebase_auth: ^0.14.0+1
  firebase_storage: ^3.0.5
  firebase_database: ^3.0.5
  firebase_analytics: ^5.0.0
  shared_preferences: ^0.5.3+4
  focused_menu: ^1.0.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
          weight: 700
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
          weight: 700